default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_' << Rails.env.upcase] %>

test:
  <<: *default
  database: <%= ENV['DB_' << Rails.env.upcase] %>
